教程部分大部分完成，提交进度
nonebot/nonebot2-tutorial pull request #2
Opened 2022-08-16 11:53 UTC by Well2333

2022-08-31 05:18 UTC, yanyongyu requested changes

2022-08-31 05:18 UTC, yanyongyu commented on 教程/插件开发（基础）/00_概览.md
> +这个时候它已经可以被称为一个插件了，尽管它还什么都没做。
这里的它缺少了指代对象`foo.py`

2022-08-31 05:18 UTC, yanyongyu commented on 教程/插件开发（基础）/00_概览.md
> +<!-- TODO: 这里放个echo插件的示例图片 -->
这里可以用现在文档的天气插件示例一样放前端聊天组件

2022-08-31 05:18 UTC, yanyongyu commented on 教程/插件开发（基础）/01_创建并加载插件.md
> +加载插件通常在机器人的入口文件进行，例如在[创建项目](<!-- TODO: 补充链接 -->)中创建的项目中的 `bot.py` 文件。在 NoneBot2 初始化完成后即可加载插件。
这里后续可能要修改，新版nb-cli默认创建的项目不包含bot.py，由nb-cli进行管理

2022-08-31 05:18 UTC, yanyongyu commented on 教程/插件开发（基础）/01_创建并加载插件.md
> +通过点分割模块名称来加载插件，通常用于加载单个插件或者是第三方插件。例如：
刚新增的功能，`load_plugin` 支持传入 `pathlib.Path` 加载插件

2022-08-31 05:18 UTC, yanyongyu commented on 教程/插件开发（基础）/01_创建并加载插件.md
> +加载一个内置插件，是 [`load_plugin`](#load_plugin) 的封装。例如：
这里可以说明一下参数是内置插件名

2022-08-31 05:18 UTC, yanyongyu commented on 教程/插件开发（基础）/01_创建并加载插件.md
> +### 其他加载方式
其实还少了个 `load_builtin_plugins`

2022-08-31 05:18 UTC, yanyongyu commented on 教程/插件开发（基础）/02_事件响应器.md
> +就像人或动物可以针对不同的外界输入做出不同的反应，例如看到了美食会流口水，被火烧到了会缩手。在 Nonebot2 中，事件响应器也可以通过一系列特定的规则精准的 **筛选** 出 **某一类型的事件**，并按照 **特定的流程** 交由 **指定的的事件处理依赖** 进行处理。
> 指定的的事件处理依赖

多了个`的`

2022-08-31 05:18 UTC, yanyongyu commented on 教程/插件开发（基础）/02_事件响应器.md
> +目前，NoneBot2 共提供了12种功能各异的辅助函数、1种具有共同命令名称前缀的命令组和1种具有共同参数的响应器组，具体内容可参考[进阶 - 事件响应器及辅助函数](../../进阶/功能/事件响应器及辅助函数.md#事件响应器的辅助函数)。
现在13种了，这里还是别写具体数字吧，随时可能变化

2022-08-31 05:18 UTC, yanyongyu commented on 教程/插件开发（基础）/02_事件响应器.md
> +matcher = on_command('天气') # 注册事件响应器
代码示例统一用black格式，这里改成双引号

2022-08-31 05:18 UTC, yanyongyu commented on 教程/插件开发（基础）/02_事件响应器.md
> +>>>>>>> Stashed changes
这里合并忘记改了吧。

2022-08-31 05:18 UTC, yanyongyu commented on 教程/插件开发（基础）/02_事件响应器.md
> +matcher = on_command('天气',aliases={'weather','tq'},priority=10,block=True)
这里也是，black改一下

2022-08-31 05:18 UTC, yanyongyu commented on 教程/插件开发（基础）/03_事件处理流程.md
> +在上一章（事件响应器）中，我们将事件响应器比作 “条件”，事件处理比作 “反射”。实际上的事件处理流程也正如反射一样，在事件响应器被触发之后会，事件被添加的处理依赖依次执行，直到所有处理依赖都执行完毕，或者遇到了某个处理依赖需要更多的事件来进行下一步的处理。在下一个事件到来并符合响应要求时，继续执行。
> 在事件响应器被触发之后会，事件被添加的处理依赖依次执行

这句不通啊

2022-08-31 05:18 UTC, yanyongyu commented on 教程/插件开发（基础）/03_事件处理流程.md
> +### 处理依赖
要不把`处理依赖`改个名字吧，总感觉有点不对，改成`处理函数`？

2022-08-31 05:18 UTC, yanyongyu commented on 教程/插件开发（基础）/03_事件处理流程.md
> +在事件响应器中，事件处理流程由一个或多个处理依赖组成，每个处理依赖都是一个 `Dependent`，详情可以参考 [进阶 - 依赖注入](../../进阶/功能/依赖注入.md)。通常我们会采用事件响应器的依赖处理装饰器来添加依赖。
`依赖处理装饰器` 这名字也改下吧

2022-08-31 05:18 UTC, yanyongyu commented on 教程/插件开发（基础）/03_事件处理流程.md
> +目前 NoneBot2 共提供了 `handle`、`recive` 和 `got` 三种依赖处理装饰器，同时也可通过其他手段为事件响应器添加处理依赖，具体内容可参考 [进阶 - 事件处理依赖及事件响应器操作](../../进阶/功能/事件处理依赖及事件响应器操作.md)。
> `recive`

typo，以及少了个`pause`

2022-08-31 05:18 UTC, yanyongyu commented on 教程/插件开发（基础）/03_事件处理流程.md
> +事件响应器操作实际上同依赖处理装饰器一样，也是作为 `Matcher` 类的[类方法](https://docs.python.org/zh-cn/3/library/functions.html?highlight=classmethod#classmethod)存在，因此事件响应器操作的调用方法也是 `Matcher.func()` 的形式。不过不同的是，事件响应器操作并不是装饰器，因此并不
这里没必要和依赖处理装饰器进行类比吧，直接说明是个类方法就行了

2022-08-31 05:18 UTC, yanyongyu commented on 教程/插件开发（基础）/03_事件处理流程.md
> +```
black代码

2022-08-31 05:18 UTC, yanyongyu commented on 教程/插件开发（基础）/03_事件处理流程.md
> +```
black代码

2022-08-31 05:18 UTC, yanyongyu commented on 教程/插件开发（基础）/03_事件处理流程.md
> +值得注意的是，在使用了 `finish` 方法之后，NoneBot2 会在向用户回复其中的消息内容后抛出 `FinishedException` 来结束事件事件响应流程的后续操作。也就是说，如果在 `finish` 被执行后，后续的程序是不会被执行的（如果你需要回复用户消息但不想事件处理流程结束，可以使用被注释的部分中展示的 `send` 方法）。
这段说明可以移出danger，放在外面，danger里保留异常捕获说明

2022-08-31 05:18 UTC, yanyongyu commented on 教程/插件开发（基础）/03_事件处理流程.md
> +目前 NoneBot2 共提供了13种事件响应器操作，其中6种可用于和用户的交互，7种仅用于流程控制，具体内容可参考 [进阶 - 事件处理依赖及事件响应器操作](../../进阶/功能/事件处理依赖及事件响应器操作.md)。
这里也没必要给出具体数字吧

2022-08-31 05:18 UTC, yanyongyu commented on 教程/插件开发（基础）/04_获取信息.md
> +在 NoneBot2 中，获取事件相关信息的途径有很多，而目前最主要的途径有两种： `调用平台API` 和 `依赖注入`。本章节中我们将介绍通过  `依赖注入` 获取信息的方法，`调用平台API`的使用方法将在[调用平台API](../插件开发（高级）/调用平台API.md)中进行介绍。
调用平台API也算获取事件信息？

2022-08-31 05:18 UTC, yanyongyu commented on 教程/插件开发（基础）/04_获取信息.md
> +在事件处理流程中，事件响应器具有自己独立的上下文，例如：当前的事件、机器人自身的信息或由其他处理依赖或事件处理流程所新增的参数等。在 NoneBot2 中，这些数据可以根据用户的需求，通过依赖注入的方式，被[依赖处理装饰器](./03_事件处理流程.md#处理依赖)注入到事件处理函数中。
并不是被依赖处理装饰器注入的，是由Matcher上下文注入的

2022-08-31 05:18 UTC, yanyongyu commented on 教程/插件开发（基础）/05_信息构造(Message).md
> +# 信息构造
Message应该叫消息吧

2022-08-31 05:18 UTC, yanyongyu commented on 教程/插件开发（基础）/05_信息构造(Message).md
> +如上方示例所示，`Message` 可以将 `str` 类型的信息转化为 `Message` 类型的信息，并进行拼接操作。
其实str可以直接和segment拼接，不需要转成Message

2022-08-31 05:18 UTC, yanyongyu commented on 教程/插件开发（基础）/05_信息构造(Message).md
> +不难发现，`Message` 的功能更多的在于消息序列层面，而对于一些非文本类消息的构建实际上起不到太大作用。而 `MessageSegment`(消息段)则是针对于 `Message` 中这一问题的解决方案。
> 对于一些非文本类消息的构建实际上起不到太大作用

这句没太理解

2022-08-31 05:18 UTC, yanyongyu commented on 教程/插件开发（基础）/05_信息构造(Message).md
> +```
这里缺少一点解释

2022-08-31 05:18 UTC, yanyongyu commented on 教程/插件开发（基础）/06_权限控制.md
> +`Permission` 可以通过识别用户的类型对其进行分类，并生成对应的 `PermissionChecker`，例如 `SUPERUSER`。在事件响应器及事件处理流程中，我们可以轻松的借助 `PermissionChecker` 对用户进行区分，以对其做出不同的回应。
> `Permission` 生成 `PermissionChecker`

这里是不是表达有误，`Permission` 是由 `PermissionChecker` 组成的

2022-08-31 05:18 UTC, yanyongyu commented on 教程/插件开发（基础）/06_权限控制.md
> +from nonebot import on_command
注意isort一下

2022-08-31 05:18 UTC, yanyongyu commented on 教程/插件开发（基础）/06_权限控制.md
> +目前，NoneBot2 仅内置了 `SUPERUSER` 一个 `PermissionChecker`，同时也可由协议适配器或用户自行定义更多的权限，并对权限进行 `或运算`。
SUPERUSER是Permission

2022-08-31 05:18 UTC, yanyongyu commented on 教程/插件开发（基础）/06_权限控制.md
> +如同 `Rule` 一样，`Permission` 也是由非负数个 `PermissionChecker` 组成的，但只需其中一个返回 `True` 时就会匹配成功。下面是自定义 `PermissionChecker` 和 `Permission` 的示例：
这里并没有在前面提到rule用法

2022-08-31 05:18 UTC, yanyongyu commented on 教程/插件开发（基础）/06_权限控制.md
> +同样地，如果想用 `Permission(*checkers)` 包裹构造 `Permission`，函数必须是异步的；但是在利用 `|`（或符号）连接构造时，NoneBot2 会自动包裹同步函数为异步函数。
这个可以删了，现在异步同步都可以

2022-08-31 05:18 UTC, yanyongyu commented on 教程/插件开发（基础）/07_优化日志.md
> +在我们开发的过程中，难免会遇到需要在后台获取某些信息来辅助开发或排查故障的情况，例如用户信息、返回值或其他相关信息。虽然我们可以使用 `print` 来将这些信息输出到控制台，但这些信息相对于NoneBot2 框架本身和其他优秀的插件所提供的日志来说并不美观，也没有其他辅助信息（例如事件、内容高亮、插件名等）。而实现这种日志效果的方法非常简单——[Loguru](https://loguru.r
> [Loguru](https://loguru.readthedocs.io/)便是您的最佳选择。

这里还是别说最佳吧，其他也有不错的库

2022-08-31 10:16 UTC, Well2333 commented on 教程/插件开发（基础）/00_概览.md
> +这个时候它已经可以被称为一个插件了，尽管它还什么都没做。
已修正

2022-08-31 10:17 UTC, Well2333 commented on 教程/插件开发（基础）/01_创建并加载插件.md
> +通过点分割模块名称来加载插件，通常用于加载单个插件或者是第三方插件。例如：
已修正

2022-08-31 14:55 UTC, Well2333 commented on 教程/插件开发（基础）/06_权限控制.md
> +如同 `Rule` 一样，`Permission` 也是由非负数个 `PermissionChecker` 组成的，但只需其中一个返回 `True` 时就会匹配成功。下面是自定义 `PermissionChecker` 和 `Permission` 的示例：
已修改，并增添超链接

2022-08-31 15:02 UTC, Well2333 commented on 教程/插件开发（基础）/01_创建并加载插件.md
> +加载插件通常在机器人的入口文件进行，例如在[创建项目](<!-- TODO: 补充链接 -->)中创建的项目中的 `bot.py` 文件。在 NoneBot2 初始化完成后即可加载插件。
目前先等待新版nb-cli的文档，并在之后对相关内容进行补充修正

2022-08-31 15:18 UTC, Well2333 commented on 教程/插件开发（基础）/05_信息构造(Message).md
> +```
个人感觉这部分其实不难理解，用过 python 自身的 format 应该都可以理解

2022-08-31 15:19 UTC, Well2333 commented on 教程/插件开发（基础）/03_事件处理流程.md
> +### 处理依赖
可更名为 `事件处理函数`

2022-08-31 15:22 UTC, Well2333 commented on 教程/插件开发（基础）/03_事件处理流程.md
> +在事件响应器中，事件处理流程由一个或多个处理依赖组成，每个处理依赖都是一个 `Dependent`，详情可以参考 [进阶 - 依赖注入](../../进阶/功能/依赖注入.md)。通常我们会采用事件响应器的依赖处理装饰器来添加依赖。
`事件处理函数装饰器` ?

2022-08-31 15:32 UTC, Well2333 commented on 教程/插件开发（基础）/03_事件处理流程.md
> +目前 NoneBot2 共提供了 `handle`、`recive` 和 `got` 三种依赖处理装饰器，同时也可通过其他手段为事件响应器添加处理依赖，具体内容可参考 [进阶 - 事件处理依赖及事件响应器操作](../../进阶/功能/事件处理依赖及事件响应器操作.md)。
已修复，但 `pause` 并不属于此类

2022-08-31 15:44 UTC, yanyongyu commented on 教程/插件开发（基础）/03_事件处理流程.md
> +目前 NoneBot2 共提供了 `handle`、`recive` 和 `got` 三种依赖处理装饰器，同时也可通过其他手段为事件响应器添加处理依赖，具体内容可参考 [进阶 - 事件处理依赖及事件响应器操作](../../进阶/功能/事件处理依赖及事件响应器操作.md)。
~~pause~~

2022-10-07 03:54 UTC, yanyongyu approved these changes

2022-10-07 03:54 UTC, merged